


const productsList = [
    { id: 1,
      category: "first",
      interest: "Animali",
      age: "6+",
      title: "Cafirstta per uccelli",
      price: "29.99 €",
      image:
        "https://www.lego.com/cdn/cs/set/assets/blt60b8b9324fadbdfd/31143.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
    },
    { id: 2,
      category: "fifth",
      interest: "Arts and Crafts",
      age: "18+",
      title: "Gandalf il Grigio e Balrog™",
      price: "19.99 €",
      image:
        "https://www.lego.com/cdn/cs/set/assets/blt625e667e3b206d20/40631.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
    },
    { id: 3,
      category: "second",
      interest: "Arte",
      age: "9+",
      title: "Aragorn™ e Arwen™",
      price: "19,99 €",
      image:
        "https://www.lego.com/cdn/cs/set/assets/blta84e06d436db4688/40632.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
    },
    { id: 4,
      category: "fourth",
      interest: "Barche",
      age: "13+",
      title: "Frodo™ e Gollum™",
      price: "14,99 €",
      image:
        "https://www.lego.com/cdn/cs/set/assets/blt66f9f99e366a124d/40630.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
    },
    { id: 5,
      category: "third",
      interest: "Arte",
      age: "18+",
      title: "Narcisi",
      price: "12,99 €",
      image:
        "https://www.lego.com/cdn/cs/set/assets/blt5b0537aa2f0c1bce/40646.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
    },
    { id: 6,
      category: "third",
      interest: "Arte",
      age: "18+",
      title: "Bouquet fiori selvatici",
      price: "59,99 €",
      image:
        "https://www.lego.com/cdn/cs/set/assets/blt474bb80770911c58/10313.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
    },
    { id: 7,
      category: "fourth",
      interest: "Arts and Crafts",
      age: "6+",
      title: "Cartolina dall'Australia",
      price: "14,99 €",
      image:
        "https://www.lego.com/cdn/cs/set/assets/blt9cdeec0032a63903/40651.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
    },
    { id: 8,
      category: "first",
      interest: "Animali",
      age: "6+",
      title: "Danzatore del leone",
      price: "9,99 €",
      image:
        "https://www.lego.com/cdn/cs/set/assets/blt29d71e0f0a2b3015/40540.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
    },
    { id: 9,
      category: "second",
      interest: "Arte",
      age: "6+",
      title: "L'albero dei soldi",
      price: "24,99 €",
      image:
        "https://www.lego.com/cdn/cs/set/assets/bltd5f0302fe3c594ea/40648_alt1.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
    },
    { id: 10,
      category: "first",
      interest: "Arts and Crafts",
      age: "6+",
      title: "Set scacchi LEGO™",
      price: "64,99 €",
      image:
        "https://www.lego.com/cdn/cs/set/assets/blt46a07a9b068b46c2/40174.jpg?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
    },
    { id: 11,
      category: "third",
      interest: "Arte",
      age: "18+",
      title: "Centrotavola di fiori secchi",
      price: "49,99 €",
      image:
        "https://www.lego.com/cdn/cs/set/assets/bltb76f113cca5cced0/10314.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
    },

    { id: 12,
      category: "fifth",
      interest: "Arte",
      age: "18+",
      title: "L'avamposto della spada",
      price: "44.99 €",
      image:
        "https://www.lego.com/cdn/cs/set/assets/blt42d6492d65b164a8/21244.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
    },
    { id: 13,
      category: "second",
      interest: "Regali di Pasqua",
      age: "6+",
      title: "Gandalf il Grigio e Balrog™",
      price: "19.99 €",
      image:
        "https://www.lego.com/cdn/cs/set/assets/blt625e667e3b206d20/40631.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
    },
    { id: 14,
      category: "first",
      interest: "Arts and Crafts",
      age: "13+",
      title: "Il Quinjet degli Avengers",
      price: "99,99 €",
      image:
        "https://www.lego.com/cdn/cs/set/assets/blte17bd71ca0739648/76248.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
    },
    { id: 15,
      category: "fifth",
      interest: "Edifici",
      age: "18+",
      title: "Millennium Falcon™",
      price: "849,99 €",
      image:
        "https://www.lego.com/cdn/cs/set/assets/blt95c35d4ed5665a49/75192.jpg?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
    },
    { id: 16,
      category: "third",
      interest: "Arte",
      age: "18+",
      title: "Negozio design e fioraio",
      price: "159,99 €",
      image:
        "https://www.lego.com/cdn/cs/set/assets/blt641f3aa0e518bae9/41732.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
    },
    { id: 17,
      category: "third",
      interest: "Arte",
      age: "18+",
      title: "Bouquet fiori selvatici",
      price: "59,99 €",
      image:
        "https://www.lego.com/cdn/cs/set/assets/blt474bb80770911c58/10313.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
    },
    { id: 18,
      category: "second",
      interest: "Arte",
      age: "6+",
      title: "Cuore ornamentale",
      price: "12,99 €",
      image:
        "https://www.lego.com/cdn/cs/set/assets/blt2b016d5b4a954e0e/40638.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
    },
    { id: 19,
      category: "third",
      interest: "Arte",
      age: "6+",
      title: "Narcisi",
      price: "12,99 €",
      image:
        "https://www.lego.com/cdn/cs/set/assets/blt5b0537aa2f0c1bce/40646.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
    },
    { id: 20,
      category: "second",
      interest: "Animali",
      age: "6+",
      title: "L'albero dei soldi",
      price: "24,99 €",
      image:
        "https://www.lego.com/cdn/cs/set/assets/bltd5f0302fe3c594ea/40648_alt1.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
    },
    { id: 21,
      category: "first",
      interest: "Edifici",
      age: "18+",
      title: "Gli appartamenti di Friends",
      price: "179,99 €",
      image:
        "https://www.lego.com/cdn/cs/set/assets/blt227c50ab0713ddf2/10292.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
    },
    { id: 22,
      category: "second",
      interest: "Arte",
      age: "18+",
      title: "Centrotavola di fiori secchi",
      price: "49,99 €",
      image:
        "https://www.lego.com/cdn/cs/set/assets/bltb76f113cca5cced0/10314.png?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1.5",
    },
  ];

  const tipiProdotto = [
    {
        "id": 1,
        "name": "Set"
    },
    {
        "id": 2,
        "name": "Home decor"
    },
    {
        "id": 3,
        "name": "Adulti"
    },
    {
        "id": 4,
        "name": "Fiori"
    },
    {
        "id": 5,
        "name": "Regali per Pasqua"
    }
]

  export { productsList, tipiProdotto };
